### ISSUE TITLE
Align scripting engine with yaup

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#47]
We probably should align the scripting engine in qDup with the scripting engine in yaup.  Yaup uses graalvm, whereas qDup is using Nashorn.

If there is no valid reason for using 2 different scripting engines, it would make sense to pick one.

**Comment by willr3** [comment]
qDup used nashorn and used a variable resolver to lookup state names when used in javascript. This let us define `foo` in the qdup state and use them in javascript e.g. `${{ foo + 10}}`
That is not available in graaljs so with graals we would have to `${{ ${{foo}} + 10}}` so that qdup will know to replace foo with the value of foo first then run the resulting javascript.
qDup currently tries to use graaljs first but will fallback to nashorn if any scripts made use of the variable resolver. We are already considering a script change for javascript evaluation to require the `${{=` prefix so I think now would be a good time to drop the variable resolver.

**Comment by willr3** [comment]
I haven't closed this yet because I would like to get `${{ foo + 10 }}` to work if `foo` is defined in `states` but recent builds are using the js scripting in yaup.

**Comment by willr3** [comment]
qDup now uses yaup's `jsEval` for javascript execution and should support `${{ foo + 10 }}` so I am closing this issue
